### ISSUE TITLE
error when opening

### ISSUE THREAD

**Issue by ThurielNemesis** [TheSR007/That_Sky_Mod_Release#2]
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\Teleport Locations\
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\Teleport Locations\Candles\
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\Teleport Locations\Wing Buffs\
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\Teleport Locations\Eden Statues\
Error: Failed to create directory: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\Languages\
Settings file created: \SteamLibrary\steamapps\common\Sky Children of the Light\mods\TSM Resources\TSM.json
TSM Loaded Successfully

**Comment by XeTrinityz** [comment]
Resolved
